### ISSUE TITLE
Could not find a delaraction file for module `@react-native-ml-kit/text-recognition`

### ISSUE THREAD

**Issue by j-elmer123** [a7medev/react-native-ml-kit#14]
### What happened?

Hi @a7medev, currently I couldn't find declaration files and couldn't import the interface/datatypes. Is there any way for me to import it correctly?

![missing-mlkit-declaration-file](https://user-images.githubusercontent.com/8566597/195767049-8536b2f6-8ace-461f-be61-f84a4efe3927.png)

### Version

@react-native-ml-kit/text-recognition:^1.2.0

### Which ML Kit packages do you use?

- [ ] @react-native-ml-kit/barcode-scanning
- [ ] @react-native-ml-kit/face-detection
- [ ] @react-native-ml-kit/identify-languages
- [ ] @react-native-ml-kit/image-labeling
- [X] @react-native-ml-kit/text-recognition
- [ ] @react-native-ml-kit/translate-text

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS

### System Information

```cli
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 955.81 MB / 15.33 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.19.1 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 25, 26, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^7.0.3 => 7.0.3 
    react: 17.0.2 => 17.0.2 
    react-native: ^0.68.3 => 0.68.3 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

- Install from yarn, `yarn add @react-native-ml-kit/text-recognition`
- Import in `.tsx` file

**Comment by a7medev** [comment]
Hi @j-elmer123, Thanks for bringing this up! The issue was that the `index.d.ts` file wasn't uploaded to NPM on publishing, I fixed that in v1.2.1.
