### ISSUE TITLE
FaceDetection Android App Crash (Can't find variable: UIManager)

### ISSUE THREAD

**Issue by juergengunz** [a7medev/react-native-ml-kit#22]
### What happened?

I get this error if I run it after install:

ReferenceError: Can't find variable: UIManager
ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

It works on iOS.

### Version

 "@react-native-ml-kit/face-detection": "^1.1.2"

### Which ML Kit packages do you use?

- [ ] @react-native-ml-kit/barcode-scanning
- [X] @react-native-ml-kit/face-detection
- [ ] @react-native-ml-kit/identify-languages
- [ ] @react-native-ml-kit/image-labeling
- [ ] @react-native-ml-kit/text-recognition
- [ ] @react-native-ml-kit/translate-text

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS

### System Information

System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 37.09 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 15.3.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.0.14 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_271 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to Reproduce

Install package and start react native

Packages Installed:

  "@invertase/react-native-apple-authentication": "^2.2.1",
    "@miblanchard/react-native-slider": "^2.1.0",
    "@react-native-community/blur": "^4.2.0",
    "@react-native-firebase/app": "^14.11.0",
    "@react-native-firebase/auth": "^14.11.0",
    "@react-native-google-signin/google-signin": "^8.0.0",
    "@react-native-ml-kit/face-detection": "^1.1.2",
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/material-top-tabs": "^6.2.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "@timwangdev/react-native-geocoder": "^1.0.0-alpha.7",
    "i18n-js": "^3.9.2",
    "mobx": "^6.5.0",
    "mobx-react-lite": "^3.3.0",
    "moment": "^2.29.3",
    "react": "17.0.2",
    "react-native": "^0.68.2",
    "react-native-actions-sheet": "github:ammarahm-ed/react-native-actions-sheet",
    "react-native-animatable": "^1.3.3",
    "react-native-bootsplash": "^4.3.2",
    "react-native-country-picker-modal": "^2.0.0",
    "react-native-date-picker": "^4.2.2",
    "react-native-device-info": "^8.7.1",
    "react-native-fast-image": "^8.6.3",
    "react-native-geolocation-service": "^5.3.0-beta.4",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-haptic-feedback": "^1.13.1",
    "react-native-iap": "^9.0.3",
    "react-native-image-crop-picker": "^0.37.3",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localize": "^2.2.1",
    "react-native-notifier": "^1.9.0",
    "react-native-onesignal": "^4.4.1",
    "react-native-pager-view": "^5.4.24",
    "react-native-permissions": "^3.3.1",
    "react-native-rate": "^1.2.9",
    "react-native-reanimated": "^2.8.0",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.13.1",
    "react-native-sensors": "^7.3.5",
    "react-native-sortable-gridview": "^1.1.5",
    "react-native-super-grid": "^4.4.0",
    "react-native-swiper": "^1.6.0-rc.3",
    "react-native-tab-view": "^3.1.1",
    "react-native-vector-icons": "^9.1.0",
    "react-usestateref": "^1.0.8",
    "socket.io-client": "^4.5.1",
    "use-dynamic-refs": "^1.0.0"

**Comment by CodingWithNobody** [comment]
Try this https://www.youtube.com/watch?v=mv4c2uTxR4U
