### ISSUE TITLE
Single example app

### ISSUE THREAD

**Issue by a7medev** [a7medev/react-native-ml-kit#23]
# Problem

The current structure treats each package as an isolated project with its own example app, this approach makes the repo pretty big and makes sharing code between packages harder.

# Solution

Creating one central example app for all the existing packages. The app will include all the packages as dependencies, it will include a screen for each package.

This makes it easy to add new packages and validate if package conflict with one another.

**Comment by CodingWithNobody** [comment]
This might help https://www.youtube.com/watch?v=gCBtvsxMu9s
