### ISSUE TITLE
unable to make build and run on ios 16.1 

### ISSUE THREAD

**Issue by usmanhashmi2123** [a7medev/react-native-ml-kit#25]
### What happened?

https://github.com/a7medev/react-native-ml-kit)/text-recognition/

integrated this in my current app which was working fine.

after adding text recognition i am unable to run the app and get error in build.
tried using the provided example still same issue.

testing on simulator i phone 14 pro ios 16.1

### Version

1.2.1

### Which ML Kit packages do you use?

- [ ] @react-native-ml-kit/barcode-scanning
- [ ] @react-native-ml-kit/face-detection
- [ ] @react-native-ml-kit/identify-languages
- [ ] @react-native-ml-kit/image-labeling
- [X] @react-native-ml-kit/text-recognition
- [ ] @react-native-ml-kit/translate-text

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS

### System Information

![Screenshot 2023-02-14 at 1 33 02 PM (2)](https://user-images.githubusercontent.com/18160933/218682779-3e29bde8-4311-46cf-8fbc-fd93950072eb.png)

System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 177.50 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.10.17.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.1 => 0.66.1 
info React Native v0.71.2 is now available (your project is running on v0.66.1)

### Steps to Reproduce

yarn add @react-native-ml-kit/text-recognition
install pods.

build the app

**Comment by CodingWithNobody** [comment]
This might help https://www.youtube.com/watch?v=gCBtvsxMu9s

**Comment by ammaarkhan** [comment]
Any update on this ? I am facing this same issue.

**Comment by a7medev** [comment]
@ammaarkhan Yes, we've already updated all the iOS dependencies to the latest versions and it will be released soon and hopefully it resolves this issue

**Comment by neethanz** [comment]
Is there any updates on this issue, still build fails in iOs.

**Comment by usmanhashmi2123** [comment]
> Is there any updates on this issue, still build fails in iOS.

i have switched to bridging.
doing it native code for ios and using that

**Comment by a7medev** [comment]
Hi everyone! v1.3.0 of `@react-native-ml-kit/text-recognition` is now out running native iOS's ML Kit v4.0.0, hopefully this resolves your issue, I'll close this one for now but feel free to reopen it if things are still broken.
