### ISSUE TITLE
GoogleMLKit/TextRecognition pods can be updated to 3.2.0

### ISSUE THREAD

**Issue by spetrey** [a7medev/react-native-ml-kit#27]
According [Google Dev docs, Text Recognition v2 is here now.](https://developers.google.com/ml-kit/vision/text-recognition/v2/ios#before_you_begin):

> Include the following ML Kit pods in your Podfile:
>
> ```
> # To recognize Latin script
> pod 'GoogleMLKit/TextRecognition', '3.2.0'
> # To recognize Chinese script
> pod 'GoogleMLKit/TextRecognitionChinese', '3.2.0'
> # To recognize Devanagari script
> pod 'GoogleMLKit/TextRecognitionDevanagari', '3.2.0'
> # To recognize Japanese script
> pod 'GoogleMLKit/TextRecognitionJapanese', '3.2.0'
> # To recognize Korean script
> pod 'GoogleMLKit/TextRecognitionKorean', '3.2.0'
> ```
>
> After you install or update your project's Pods, open your Xcode project using its .xcworkspace. ML Kit is supported in Xcode version 12.4 or greater.

**Comment by spetrey** [comment]
Turns out these pods can actually be updated to 4.0.0. I guess their documentation is a little behind. See Google's samples here: https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/Podfile#L6-L19

**Comment by a7medev** [comment]
Thanks for pointing this out. I'll review the PR you created which will resolve this issue.
