### ISSUE TITLE
If image is rotated by 180 then unable to read the text

### ISSUE THREAD

**Issue by Punit-Vajpeyi** [a7medev/react-native-ml-kit#31]
### What happened?

If we select the reverse image then text recognition is not correct, we should have facility to rotate the image and read the exact content.

### Version

@react-native-ml-kit/barcode-scanning: *version*@react-native-ml-kit/face-detection: *version*@react-native-ml-kit/identify-languages: *version*@react-native-ml-kit/image-labeling: *version*@react-native-ml-kit/text-recognition: *version*@react-native-ml-kit/translate-text: *version*

### Which ML Kit packages do you use?

- [ ] @react-native-ml-kit/barcode-scanning
- [ ] @react-native-ml-kit/face-detection
- [ ] @react-native-ml-kit/identify-languages
- [ ] @react-native-ml-kit/image-labeling
- [X] @react-native-ml-kit/text-recognition
- [ ] @react-native-ml-kit/translate-text

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS

### System Information

System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M2
    Memory: 105.91 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9971841
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.11 => 0.71.11 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to Reproduce

Select reverse image from gallery and send the image url to text recognise function, its giving reverse text.

**Comment by a7medev** [comment]
Hi @Punit-Vajpeyi! This package utilizes Google's ML Kit library, these models are pre-trained, and we're restricted by the set of features provided by ML Kit.
