### ISSUE TITLE
Publish the latest text-recognition changes to npm?

### ISSUE THREAD

**Issue by SMJ93** [a7medev/react-native-ml-kit#37]
### What happened?

Can you publish the latest updates to npm please?

The latest version: 1.2.1 was published 11 months ago.

### Version

@react-native-ml-kit/barcode-scanning: *version*@react-native-ml-kit/face-detection: *version*@react-native-ml-kit/identify-languages: *version*@react-native-ml-kit/image-labeling: *version*@react-native-ml-kit/text-recognition: *version*@react-native-ml-kit/translate-text: *version*

### Which ML Kit packages do you use?

- [ ] @react-native-ml-kit/barcode-scanning
- [ ] @react-native-ml-kit/face-detection
- [ ] @react-native-ml-kit/identify-languages
- [ ] @react-native-ml-kit/image-labeling
- [X] @react-native-ml-kit/text-recognition
- [ ] @react-native-ml-kit/translate-text

### What platforms are you seeing this issue on?

- [X] Android
- [X] iOS

### System Information

N/A

### Steps to Reproduce

N/A

**Comment by SMJ93** [comment]
fyi @vonovak

**Comment by a7medev** [comment]
Hi @SMJ93! v1.3.0 of `@react-native-ml-kit/text-recognition` is now out! 🚀
