### ISSUE TITLE
Upgrade GoogleMLKit/FaceDetection to 6.0.0

### ISSUE THREAD

**Issue by allangomessl** [a7medev/react-native-ml-kit#52]
### What happened?

I'm using `FaceDetection` with `google-signin` and their are with conflict on `GTMSessionFetcher`

```
[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In snapshot (Podfile.lock):
    GTMSessionFetcher/Core (< 4.0, = 3.4.1, >= 3.3, >= 3.3.2, ~> 3.3)

  In Podfile:
    RNGoogleSignin (from `../node_modules/@react-native-google-signin/google-signin`) was resolved to 12.2.1, which depends on
      GoogleSignIn (~> 7.1) was resolved to 7.1.0, which depends on
        GTMSessionFetcher/Core (~> 3.3)

    RNMLKitFaceDetection (from `../node_modules/@react-native-ml-kit/face-detection`) was resolved to 1.3.1, which depends on
      GoogleMLKit/FaceDetection (= 4.0.0) was resolved to 4.0.0, which depends on
        MLKitFaceDetection (~> 3.0.0) was resolved to 3.0.0, which depends on
          MLKitVision (~> 5.0) was resolved to 5.0.0, which depends on
            GTMSessionFetcher/Core (< 3.0, >= 1.1)
```

To resolve this problem we need upgrade `GoogleMLKit/FaceDetection` to `6.0.0`

### Version

@react-native-ml-kit/face-detection: ^1.3.1

### Which ML Kit packages do you use?

- [ ] @react-native-ml-kit/barcode-scanning
- [X] @react-native-ml-kit/face-detection
- [ ] @react-native-ml-kit/identify-languages
- [ ] @react-native-ml-kit/image-labeling
- [ ] @react-native-ml-kit/text-recognition
- [ ] @react-native-ml-kit/translate-text

### What platforms are you seeing this issue on?

- [ ] Android
- [X] iOS

### System Information

System:
  OS: macOS 14.3
  CPU: (8) arm64 Apple M1
  Memory: 106.59 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: ~/.local/share/mise/installs/node/20/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.4
    path: ~/.local/share/mise/installs/node/20/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/ag/.local/share/mise/installs/ruby/2.7.3/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /Users/ag/.local/share/mise/installs/java/temurin-17/bin/javac
  Ruby:
    version: 2.7.3
    path: /Users/ag/.local/share/mise/installs/ruby/2.7.3/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.2
    wanted: 0.74.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to Reproduce

```
npx expo install @react-native-google-signin/google-signin
npx expo install @react-native-ml-kit/face-detection
npx pod-install
```

**Comment by allangomessl** [comment]
PR opened
https://github.com/a7medev/react-native-ml-kit/pull/53

**Comment by a7medev** [comment]
I think we can close this issue now that #53 has been merged, I'll work on the release ASAP.
